{% set version = "2.4.0" %}

package:
  name: aioeasywebdav
  version: {{ version }}

source:
  fn: aioeasywebdav-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/aioeasywebdav/aioeasywebdav-{{ version }}.tar.gz
  sha256: 216aa71e76bf810c2293fec93922475a532af999fce89b37b6788f0c237981ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6                        # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - python >=3.6
    - aiohttp
    - setuptools-scm

test:
  imports:
    - aioeasywebdav

about:
  home: https://gitlab.alelec.net/corona/aioeasywebdav
  license: ISC
  license_file: LICENSE
  summary: A straight-forward WebDAV client, ported from easywebdav to use aiohttp.
  dev_url: https://gitlab.alelec.net/corona/aioeasywebdav
  description: |
    This project started as a port of the requests-based EasyWebDAV
    (http://github.com/amnong/easywebdav) to asyncio on Python 3.5. It has
    since been extended with additional features.

extra:
  recipe-maintainers:
    - johanneskoester
