appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: F/qPZHyH0y4OIUMBjPBRBSXyLNhOG+VQWWZtEq7jpwJnGkgT1X3Sc/7YSAsU52qt9G7uzfUo1AGFI5cJxDxkvqwFiGZTcTxe9CK/13Cb7NMMZ9vFbNiIarvfxgvvMMDbcmKSpBlxgQ2Ms7HuLUUdFUJ9wE8dLbzZNPJ17IusGbwPXT9CuU6cW05nrpWP3HVySmKyWJdc0PJ7iwdmQknZ0YXT7fq76FUy3iszI2ll9zGJzuDqXb1ICNDvmAQh5fnPGrnlkTPe4mVN4ZnEBtyMOiM9HJB1qmA1sSXcyGEV/sHX8z6liDPbvl60LMeFKVFETPBm2hujn4nxa288Bz+2OSM2Xs49CknPg/Ctjx73Sv5AYigpn3L8aaDA1CzPLi9QRb6LUCvETUVAPA+7h4qbZsdlFjOm/GTQ+EMCA3dIO/UOJ2hTu8M4FMkEARLtR0wxBFn1bPHZ/3HMEYyTBNqsz0Qx8IS+xfgBQLv167fpPUgHHwguFQE2CJPlHPcow+Y75JMd5+sgkdh+3zm/qnp6/b2s+2uo/SDjq/RsnErcUFrec3iGd0V7ZmgGAdi71l9H0wG9pS5SUPQ/vBA3/l3yDDlK51tHsb0MXnB4bNxNlnzRDo1BiiSQypiSIndPAElpo3czyb6aKaODqJWs453xgOEwN+Gt/ECZPU8tiMgOzX8=}
provider:
  win: azure
