travis:
  secure:
    BINSTAR_TOKEN: ovzk88E4RkaDYSCVS2f7F1U2KHHojY33jCbk0gKEs0r4t6I3UAO9r8PtGK3bcKwNffAfy/uDD5DDiyip6cIXs/z6pPp9oiFxmgf2nIFfMvCpJEm9FZEw6P99updJRKbCyg0EuxZQGPepea9q6ES7RPmSGjs74otnSa6aRYEllJffhqZ3HJTfQY4Nfdq1kN7421QqdWIy6PpTTtZZ9ELkIiXyGIz/YR+kr5DGvmWYczjzNFCtq1slv0EImBH5DwSgf84GctHERzZDDedQmV7Cn+HekZPnmSDOZajSR00WnUtGiaOXR1r12Z9Vl9GyNBGTM4KHcmqCSoz9dXWZi918hzx/+fSeTgKRK5jLHjiYpSYUTtFKQ6FaU30k8w2vcKvLNpyvk6NnkqXrO+jnruZvabU2K6pogYknCj2Orf5icsWdObgKEhE4/Tx5d5yKOD2jPC76iSYIC6R+jblODmK9h02ijeCtOqVvNtpL7IraFYYe+8DXc5QxMOkVkJavjlQZJYgsAHbIYhsgWnzweR9Ldhm5jnwjfcMnOSFkwpnTEXtNzqlfZpJIDHNnkGeILJXS/EI27P3TREepujMKOYw1WXQ18P91LLQDrF5tqz+f5GFbmaku4BDDP+EgNTNC/vDSTzNI3/O819vD64TkhAOUtyKmQiSr6sjaOdgkvua66e0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
